### ISSUE TITLE
Repository todo tracker

### ISSUE THREAD

**Issue by patrickcping** [patrickcping/pingone-go#5]
## CI
- [ ] Build validation CI
- [ ] Codegen validation CI
- [ ] Changelog build process
- [ ] Release/tagging process

## Documentation
- [ ] Getting started
- [ ] Contributing guide
- [ ] Changelog process
- [ ] PR checklist

## Contribution
- [ ] Issue template
- [ ] PR template
